version: "3.8"
services:
  web:
    build: .
    command: gunicorn app:app -b 0.0.0.0:8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  worker:
    build: .
    command: python3 main.py
    restart: unless-stopped
